### ISSUE TITLE
Problems to arm 

### ISSUE THREAD

**Issue by wolfcam** [guerrerotook/securitas-direct-new-api#114]
After configure Securitas Account ( Verisure BR), i'm trying do arm but received this:

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/securitas/alarm_control_panel.py:209
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: 12:27:37 (4 occurrences)
Last logged: 12:44:30

[139982296663760] 'str' object has no attribute 'operation_status'
[139981516031312] 'str' object has no attribute 'operation_status'
[139982274797792] 'str' object has no attribute 'operation_status'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 968, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 720, in _handle_entity_call
    await result
  File "/config/custom_components/securitas/alarm_control_panel.py", line 323, in async_alarm_arm_home
    await self.set_arm_state("ARMDAY1")
  File "/config/custom_components/securitas/alarm_control_panel.py", line 209, in set_arm_state
    while arm_status.operation_status == "WAIT":
AttributeError: 'str' object has no attribute 'operation_status'

**Comment by wolfcam** [comment]
I put some ERROR in alarm_control_panel.py:

                arm_status: ArmStatus = await self.client.session.check_arm_status(
                    self.installation,
                    response[1],
                    state,
                    count,
                    self._get_proto_status(),
                )
                _LOGGER.error("RAW ARM STATUS", arm_status)
                
 and return this:

Bad logger message: RAW ARM STATUS: (('Detector de acesso com tecnologia Shocksensor >> porta fundos',))
Bad logger message: RAW ARM STATUS: ((ArmStatus(operation_status='WAIT', message='Pedido em processamento', status=None, InstallationNumer=None, protomResponse=None, protomResponseData=None, requestId='_pollingStatus_327515', error=None),))

**Comment by guerrerotook** [comment]
I add some code in the past for this and show a notification in the Home Assistant UI. Did you get a notification?

**Comment by wolfcam** [comment]
I received a notification also i saw that notification indicate that my alarm had a least one sensor open and fail to trigger alarm.
