### ISSUE TITLE
Problema al armado

### ISSUE THREAD

**Issue by CJHive** [guerrerotook/securitas-direct-new-api#128]
Desde hace 2 días me da este error al armar la alarma 

Detalles de registro (ERROR)
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/securitas/alarm_control_panel.py:209
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:54:26 (1 occurrences)
Last logged: 18:54:26

[139787163709984] 'str' object has no attribute 'operation_status'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 199, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 686, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 961, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 726, in _handle_entity_call
    await result
  File "/config/custom_components/securitas/alarm_control_panel.py", line 325, in async_alarm_arm_home
    await self.set_arm_state("ARMDAY1")
  File "/config/custom_components/securitas/alarm_control_panel.py", line 209, in set_arm_state
    while arm_status.operation_status == "WAIT":
AttributeError: 'str' object has no attribute 'operation_status'

![Screenshot_20230316_185427_Home Assistant](https://user-images.githubusercontent.com/42096806/225710584-5ddc3cc1-aa61-4d6f-8c1e-2739505b1a01.jpg)

**Comment by CJHive** [comment]
También veo este error 

Logger: custom_components.securitas.securitas_direct_new_api.apimanager
Source: custom_components/securitas/securitas_direct_new_api/apimanager.py:193
Integration: Securitas Direct ([documentation](https://github.com/guerrerotook/securitas-direct-new-api), [issues](https://github.com/guerrerotook/securitas-direct-new-api/issues))
First occurred: 19:12:01 (1 occurrences)
Last logged: 19:12:01

Unauthorized

**Comment by CJHive** [comment]
Tenía un problema en una zona que se quedaba en abierta. Sería bueno cambiar este error por algo como zona abierta
