### ISSUE TITLE
Error doing job: Future exception was never retrieved

### ISSUE THREAD

**Issue by alessbarb** [guerrerotook/securitas-direct-new-api#20]
Buenas, me salen algunos errores en Home Assistant, este es uno de ellos:

```
Logger: homeassistant
Source: custom_components/securitas/__init__.py:135
Integration: Securitas Direct (documentation, issues)
First occurred: 19:22:40 (1 occurrences)
Last logged: 19:22:40

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/securitas/alarm_control_panel.py", line 56, in setup_platform
    current_state: CheckAlarmStatus = hub.update_overview(
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 195, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/securitas/__init__.py", line 135, in update_overview
    while alarm_status.operationStatus == "WAIT":
AttributeError: 'str' object has no attribute 'operationStatus'
```

**Comment by guerrerotook** [comment]
He añadido código para gestionar esa excepción.
