### ISSUE TITLE
Can't Disarm

### ISSUE THREAD

**Issue by bilbon0bud** [guerrerotook/securitas-direct-new-api#224]
Hello

I can arm my alarm, but i can't disarm.
i have perimetric mode too.

here are my logs

2024-04-05 11:49:27.249 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Authentication token expires 2024-04-05 11:58:41 and now is 2024-04-05 11:49:27.249814
2024-04-05 11:49:27.250 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Capabilities token expires 2024-04-05 11:58:41 and now is 2024-04-05 11:49:27.250181
2024-04-05 11:49:27.250 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Making request xSDisarmPanel with device_id aa1e25ac73eb4479, uuid aa1e25ac73eb4479 and idDeviceIndigitall 
2024-04-05 11:49:27.444 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] --------------Response--------------
2024-04-05 11:49:27.445 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"errors":[{"message":"4: Requested data not found error.","name":"ApiError","time_thrown":"2024-04-05T09:49:27.423Z","data":{"res":"ERROR","err":"4","status":404},"path":["xSDisarmPanel"]}],"data":{"xSDisarmPanel":null}}

2024-04-05 11:49:27.445 INFO (MainThread) [custom_components.securitas.alarm_control_panel] ('4: Requested data not found error.', {'errors': [{'message': '4: Requested data not found error.', 'name': 'ApiError', 'time_thrown': '2024-04-05T09:49:27.423Z', 'data': {'res': 'ERROR', 'err': '4', 'status': 404}, 'path': ['xSDisarmPanel']}], 'data': {'xSDisarmPanel': None}}, {'app': '{"appVersion": "10.102.0", "origin": "native"}', 'User-Agent': 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.41', 'X-APOLLO-OPERATION-ID': '%BIG_TOKEN%', 'auth': '{"loginTimestamp": 1712310222025, "user": "%USERNAME%", "id": "OWA_______________"%USERNAME%_______________2024451149250397", "country": "FR", "lang": "fr", "callby": "OWA_10", "hash": "%HASH%"}'}, {'operationName': 'xSDisarmPanel', 'variables': {'request': 'DARM1DARMPERI', 'numinst': '%NUM%', 'panel': 'SDVFAST', 'currentStatus': 'E'}, 'query': 'mutation xSDisarmPanel($numinst: String!, $request: DisarmCodeRequest!, $panel: String!) {\n  xSDisarmPanel(numinst: $numinst, request: $request, panel: $panel) {\n    res\n    msg\n    referenceId\n  }\n}\n'})
2024-04-05 11:49:27.446 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Authentication token expires 2024-04-05 11:58:41 and now is 2024-04-05 11:49:27.446314
2024-04-05 11:49:27.446 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Capabilities token expires 2024-04-05 11:58:41 and now is 2024-04-05 11:49:27.446581
2024-04-05 11:49:27.446 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Making request CheckAlarm with device_id aa1e25ac73eb4479, uuid aa1e25ac73eb4479 and idDeviceIndigitall 
2024-04-05 11:49:27.802 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] --------------Response--------------
2024-04-05 11:49:27.802 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"data":{"xSCheckAlarm":{"res":"OK","msg":"alarm-manager.processed.request","referenceId":"fc082c63-92c6-4844-bf81-8cf2adc4a41d"}}}

2024-04-05 11:49:28.803 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Authentication token expires 2024-04-05 11:58:41 and now is 2024-04-05 11:49:28.803750
2024-04-05 11:49:28.804 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Capabilities token expires 2024-04-05 11:58:41 and now is 2024-04-05 11:49:28.804067
2024-04-05 11:49:30.805 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Making request CheckAlarmStatus with device_id aa1e25ac73eb4479, uuid aa1e25ac73eb4479 and idDeviceIndigitall 
2024-04-05 11:49:30.890 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] --------------Response--------------
2024-04-05 11:49:30.890 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"data":{"xSCheckAlarmStatus":{"res":"WAIT","msg":"alarm-manager.processing.request","status":null,"numinst":null,"protomResponse":null,"protomResponseDate":null}}}
2024-04-05 11:49:32.891 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Making request CheckAlarmStatus with device_id aa1e25ac73eb4479, uuid aa1e25ac73eb4479 and idDeviceIndigitall 
2024-04-05 11:49:32.970 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] --------------Response--------------
2024-04-05 11:49:32.970 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"data":{"xSCheckAlarmStatus":{"res":"WAIT","msg":"alarm-manager.processing.request","status":null,"numinst":null,"protomResponse":null,"protomResponseDate":null}}}
2024-04-05 11:49:34.971 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Making request CheckAlarmStatus with device_id aa1e25ac73eb4479, uuid aa1e25ac73eb4479 and idDeviceIndigitall 
2024-04-05 11:49:35.107 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] --------------Response--------------
2024-04-05 11:49:35.107 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"data":{"xSCheckAlarmStatus":{"res":"OK","msg":"alarm-manager.status_panel.active_perimetral_alarm_msg","status":null,"numinst":null,"protomResponse":"E","protomResponseDate":"2024-04-05T09:49:33Z"}}}

**Comment by SirLouen** [comment]
It has been failing the same for me lately.

It appears that there are some issues with authentication because after some intents if I go to the web, there is a blocking message by their anti-login error system:

![image](https://github.com/guerrerotook/securitas-direct-new-api/assets/224787/94af6327-ab26-47c8-9bb4-9b0e5e9c8b28)

**Comment by cantupaz** [comment]
@bilbon0bud Do you still have the problem? Sometimes trying a little while later clears issues. If you're still having problems, does your installation have sensors outside (a perimetral alarm)? The logs you sent show that the integration is using the commands for a system with perimetral alarm, but those commands are different for a system without perimetral.

**Comment by bilbon0bud** [comment]
Hello

now i can’t arm or disarm.
I have an outside perimeter alarm.

I can show the status of the alarm only.

‘Best regards

**Comment by cantupaz** [comment]
Are you using the latest version of the integration?

Could you send logs of the arming failure? I'm curious to see if you also get a 404 error or something else.

The status in HA is correct and changes after you arm/disarm in the official app?

**Comment by bilbon0bud** [comment]
I ll send you logs in 2 or 3 hours.

**Comment by bilbon0bud** [comment]
Here are the logs

**Comment by bilbon0bud** [comment]
here are the logs when arming

2024-04-27 14:31:12.424 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Making request xSArmPanel with device_id 06d2a33a2cd1472a, uuid 06d2a33a2cd1472a and idDeviceIndigitall 
2024-04-27 14:31:12.692 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Making request CheckAlarmStatus with device_id 06d2a33a2cd1472a, uuid 06d2a33a2cd1472a and idDeviceIndigitall 
2024-04-27 14:31:12.696 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] --------------Response--------------
2024-04-27 14:31:12.696 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"errors":[{"message":"alarm-manager.alarm_process_error","name":"ApiError","time_thrown":"2024-04-27T12:31:12.671Z","data":{"res":"ERROR","err":"10","status":500},"path":["xSArmPanel"]}],"data":{"xSArmPanel":null}}

2024-04-27 14:31:12.696 INFO (MainThread) [custom_components.securitas.alarm_control_panel] ('alarm-manager.alarm_process_error', {'errors': [{'message': 'alarm-manager.alarm_process_error', 'name': 'ApiError', 'time_thrown': '2024-04-27T12:31:12.671Z', 'data': {'res': 'ERROR', 'err': '10', 'status': 500}, 'path': ['xSArmPanel']}], 'data': {'xSArmPanel': None}}, {'app': '{"appVersion": "10.102.0", "origin": "native"}', 'User-Agent': 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.124 Safari/537.36 Edg/102.0.1245.41', 'X-APOLLO-OPERATION-ID': 'd753753b90d368c06d607fdddc56c3c5c00782a60e9eef86021b6dbf2b5c0b7bf1c4ef4ebc1a8779787dde92c342e98fe08e2455a79837eb0ab9bc344fe94e20', 'X-APOLLO-OPERATION-NAME': 'xSArmPanel', 'extension': '{"mode":"full"}', 'numinst': '%NUM%', 'panel': 'SDVFAST', 'X-Capabilities': 'eyJhbGciOiJIUzI1NiJ9.eyJqdGkiOiI3OWQ3ODVmYi0wN2U2LTQyNDAtODJlNC03NTEyMThkM2E1YWQiLCJpYXQiOjE3MTQyMjA0NTIsImV4cCI6MTcxNDIyMTM1Miwicm9sZSI6IlJFU1RSSUNURUQiLCJpbnMiOiIxNDM1ODI4IiwiY2FwIjpbIkVTVElOViIsIkFSTURBWSIsIkFSTU5JR0hUIiwiUEVSSSIsIkFSTSIsIkdDIiwiQVNJIiwiRVNUIiwiREFSTSIsIklNRyIsIk5PVCIsIkFDVCIsIkNPTkYiLCJDQUxMUklORyIsIkhPTUVNT1ZFIiwiU01BUlROT1QiLCJLRVkiLCJDQU1FUkFTIiwiUExBTiIsIk1ZU0QiLCJQQU5FTENPTkYiLCJTQ0giLCJJTlNUV09SRFMiLCJDT05GU0VSViIsIkNPTkZaT05FUyIsIlBBWU1FTlRHIiwiV0hBVE5FVyIsIkNPTlRNR1JNWVNFUlYiLCJUSU1FTElORSIsIk5PVENPTkYiLCJERVZJQ0VTQ09ORiIsIlJFTUlOREVSUyIsIklOQVBQQ0FNUEFJR04iLCJNQUlMQk9YIiwiQ0FMTCIsIktFWVNSRVBPUlQiLCJBUk1JTlRGUEFSVCIsIkFSTVBBUlRGSU5UIiwiREVBQ1RJVkFURVpPTkUiXX0.O2_LkIMNQ9j93BMGLdIX0SPILPFCsUCph_wTpCBA6_4', 'auth': '{"loginTimestamp": 1714220452357, "user": "%USERNAME%", "id": "OWA_______________%USERNAME%_______________20244271431424338", "country": "FR", "lang": "fr", "callby": "OWA_10", "hash": "eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJoYXBnbjkzIiwiY250IjoiRlIiLCJjYnkiOiJPV0FfMTAiLCJ2ZXIiOiIxMC4xMDIuMCIsInVzcmlkIjoiNjA1NzYyOCIsImp0aSI6IjYxNDFjODM3LTRhYTItNDMwNS1hOWUxLWYzMmQxYTk2OGYzZiIsImlhdCI6MTcxNDIyMDQ1MiwiZXhwIjoxNzE0MjIxMzUyfQ.awVjSGHUmrziQZtTt7EiNeQ-f9ZCWrMkp4ylN5Y-UbE"}'}, {'operationName': 'xSArmPanel', 'variables': {'request': 'ARMDAY1', 'numinst': '%NUM%', 'panel': 'SDVFAST', 'currentStatus': 'D'}, 'query': 'mutation xSArmPanel($numinst: String!, $request: ArmCodeRequest!, $panel: String!, $currentStatus: String) {\n  xSArmPanel(numinst: $numinst, request: $request, panel: $panel, currentStatus: $currentStatus) {\n    res\n    msg\n    referenceId\n  }\n}\n'})
2024-04-27 14:31:12.792 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] --------------Response--------------
2024-04-27 14:31:12.792 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"data":{"xSCheckAlarmStatus":{"res":"WAIT","msg":"alarm-manager.processing.request","status":null,"numinst":null,"protomResponse":null,"protomResponseDate":null}}}

2024-04-27 14:31:14.794 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Making request CheckAlarmStatus with device_id 06d2a33a2cd1472a, uuid 06d2a33a2cd1472a and idDeviceIndigitall 
2024-04-27 14:31:14.929 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] --------------Response--------------
2024-04-27 14:31:14.930 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"data":{"xSCheckAlarmStatus":{"res":"OK","msg":"alarm-manager.inactive_alarm","status":null,"numinst":null,"protomResponse":"D","protomResponseDate":"2024-04-27T12:31:14Z"}}}

**Comment by guerrerotook** [comment]
The message is _4: Requested data not found error_ and it's 500 error from their side, so there is nothing much that we can do here.

**Comment by bilbon0bud** [comment]
But everything work from the Verisure app or web…

**Comment by cantupaz** [comment]
And you can see the status change in HA when you arm or disarm in the official app?

Have you tried logging out and then logging in in the HA integration?

**Comment by bilbon0bud** [comment]
The status are ok in ha When I change them by the app.

I have try many times to log out and relog or to reinstall the ha app. But … nothing change

**Comment by cantupaz** [comment]
I managed to get a 500 error after blocking my account on purpose. After unblocking I have problems similar to what you're having. But I'm also seem to have been flagged as a robot.... I'll try later.

**Comment by SirLouen** [comment]
My theory is that the Error 500 comes after a ton of failed authentications. So I think that the debug should be done way earlier, just before the first authentication begins. If I have some time I will start with this because it's killing me not having my automation in place for so long (I've lost the use of disarming in the morning, and it triggers accidentally every other morning)

**Comment by bilbon0bud** [comment]
@SirLouen Same problem for me.

**Comment by Cobretti75** [comment]
Hello. I have the same problem and what I can say is that it happened after changing the Securitas Direct password and having to reinstall the integration to be able to put the new password in the configuration. Has anyone been able to solve this problem?

**Comment by Cobretti75** [comment]
> Changing from DARM1DARMPERI to DARM1 made it work for me.
> 
> No idea why this request uses that const even though i unchecked the "peri" option.

Where can I change it?

**Comment by Cobretti75** [comment]
Hello. Something has changed, let’s see if you can help us solve this problem. After the last update, that's the error that I receive when I try to disarm: "TypeError: 'NoneType' object is not subscriptable".

I also put here what appears in the record:

Registrador: homeassistant.components.websocket_api.http.connection
Fuente: components/websocket_api/commands.py:245
integración: Home Assistant WebSocket API (documentación, problemas)
Ocurrió por primera vez: 00:17:26 (3 ocurrencias)
Última vez registrado: 00:37:21

[140652816873312] Unexpected exception
[140652569761760] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 284, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
  File "/config/custom_components/securitas/alarm_control_panel.py", line 239, in async_alarm_disarm
    disarm_status = await self.client.session.disarm_alarm(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.installation
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 706, in disarm_alarm
    if response["res"] != "OK":
       ~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by guerrerotook** [comment]
Thanks for the message, I also notices this error in my installation as well. I think it's related to the expired token. Let me add some code to handle this and notify the UI with the error so we can know more.

**Comment by Cobretti75** [comment]
Thank you very much for the quick response and the solution. However, after this update, I now get another different error, which makes it still impossible for me to disarm the alarm:

Registrador: homeassistant.components.websocket_api.http.connection
Fuente: components/websocket_api/commands.py:245
integración: Home Assistant WebSocket API (documentación, problemas)
Ocurrió por primera vez: 01:35:39 (1 ocurrencias)
Última vez registrado: 01:35:39

[140256319472832] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 284, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
  File "/config/custom_components/securitas/alarm_control_panel.py", line 239, in async_alarm_disarm
    disarm_status = await self.client.session.disarm_alarm(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.installation
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 706, in disarm_alarm
    if "res" in response and response["res"] != "OK":
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by Cobretti75** [comment]
> Thanks for the message, I also notices this error in my installation as well. I think it's related to the expired token. Let me add some code to handle this and notify the UI with the error so we can know more.

Thank you very much for the quick response and the solution. However, after this update, I now get another different error, which makes it still impossible for me to disarm the alarm:

Registrador: homeassistant.components.websocket_api.http.connection
Fuente: components/websocket_api/commands.py:245
integración: Home Assistant WebSocket API (documentación, problemas)
Ocurrió por primera vez: 01:35:39 (1 ocurrencias)
Última vez registrado: 01:35:39

[140256319472832] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 284, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
  File "/config/custom_components/securitas/alarm_control_panel.py", line 239, in async_alarm_disarm
    disarm_status = await self.client.session.disarm_alarm(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.installation
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 706, in disarm_alarm
    if "res" in response and response["res"] != "OK":
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
