### ISSUE TITLE
añadir cerradura electrónica

### ISSUE THREAD

**Issue by hlas** [guerrerotook/securitas-direct-new-api#234]
Hola

¿Sería posible añadir la apertura y cierre de la nueva cerradura eléctronica de SD?
He capturado las llamadas a la API:

`{
    "operationName": "xSGetSmartlockConfig",
    "variables": {
        "numinst": "XXXXXXX",
        "panel": "SDVECUW",
        "devices": [
            {
                "deviceType": "DR",
                "deviceId": "01",
                "keytype": "0"
            }
        ]
    },
    "query": "query xSGetSmartlockConfig($numinst: String!, $panel: String!, $devices: [SmartlockDevicesInfo]!) {\n  xSGetSmartlockConfig(numinst: $numinst, panel: $panel, devices: $devices) {\n    res\n    referenceId\n    zoneId\n    serialNumber\n    location\n    family\n    type\n    label\n    features {\n      holdBackLatchTime\n      calibrationType\n      autolock {\n        active\n        timeout\n      }\n    }\n  }\n}"
}`

Respuesta:
`{
    "data": {
        "xSGetSmartlockConfig": [
            {
                "res": "OK",
                "referenceId": null,
                "zoneId": "DR01",
                "serialNumber": "XXXXXXX",
                "location": "Pl_1_Recibidor",
                "family": "User",
                "type": "163",
                "label": "Cerradura",
                "features": {
                    "holdBackLatchTime": 3,
                    "calibrationType": 0,
                    "autolock": {
                        "active": true,
                        "timeout": "1800"
                    }
                }
            }
        ]
    }
}`

Apertura:

`{
    "operationName": "xSChangeSmartlockMode",
    "variables": {
        "numinst": "XXXXXXX",
        "panel": "SDVECUW",
        "deviceId": "01",
        "deviceType": "DR",
        "lock": false
    },
    "query": "mutation xSChangeSmartlockMode($numinst: String!, $panel: String!, $deviceId: String!, $deviceType: String!, $lock: Boolean!) {\n  xSChangeSmartlockMode(\n    numinst: $numinst\n    panel: $panel\n    deviceId: $deviceId\n    deviceType: $deviceType\n    lock: $lock\n  ) {\n    res\n    msg\n    referenceId\n  }\n}"
}`

Respuesta:

`{
    "data": {
        "xSChangeSmartlockMode": {
            "res": "OK",
            "msg": "Your request has been sent",
            "referenceId": "OWP______________XXXXXX__XXXXXXXX________________"
        }
    }
}`

`{
    "operationName": "xSChangeSmartlockModeStatus",
    "variables": {
        "numinst": "xxxxxxx",
        "panel": "SDVECUW",
        "deviceId": "01",
        "referenceId": "OWP_______________xxxxx_xxxxxxx_______________",
        "counter": 1
    },
    "query": "query xSChangeSmartlockModeStatus($numinst: String!, $panel: String!, $referenceId: String!, $deviceId: String, $counter: Int) {\n  xSChangeSmartlockModeStatus(\n    numinst: $numinst\n    panel: $panel\n    referenceId: $referenceId\n    counter: $counter\n    deviceId: $deviceId\n  ) {\n    res\n    msg\n    protomResponse\n    status\n  }\n}"
}`

`{
    "data": {
        "xSChangeSmartlockModeStatus": {
            "res": "WAIT",
            "msg": "Request in progress, please wait",
            "protomResponse": null,
            "status": null
        }
    }
}
`

Y al final:

`{
    "data": {
        "xSChangeSmartlockModeStatus": {
            "res": "OK",
            "msg": "Request processed correctly",
            "protomResponse": null,
            "status": "procesed"
        }
    }
}`

Y para el cierre:

`{
    "operationName": "xSChangeSmartlockMode",
    "variables": {
        "numinst": "xxxxxxx",
        "panel": "SDVECUW",
        "deviceId": "01",
        "deviceType": "DR",
        "lock": true
    },
    "query": "mutation xSChangeSmartlockMode($numinst: String!, $panel: String!, $deviceId: String!, $deviceType: String!, $lock: Boolean!) {\n  xSChangeSmartlockMode(\n    numinst: $numinst\n    panel: $panel\n    deviceId: $deviceId\n    deviceType: $deviceType\n    lock: $lock\n  ) {\n    res\n    msg\n    referenceId\n  }\n}"
}`

**Comment by bigramonk** [comment]
Hola,
Reconocí mi cerradura en la publicidad de Securitas. Parece ser una [**Danalock V3-BTZE**](https://www.securitas.is/wp-content/uploads/2022/02/79473cca-3624-4771-b08e-8dce8c1accf5.pdf) (Zigbee y Bluetooth), aunque haya [varios modelos](https://danalock.com/hrf_faq/what-are-the-differences-between-the-danalock-v3-variants) y que en España se pueda distribuir otro.
Si fuera el caso, creo que podría ser más sencillo ver qué protocolo usa Veritas e intentar integrar el otro directamente con Home Assistant (con zigbee2mqtt o con un bluetooth proxy).
Así no tendrías ningún tipo de latencia al abrir o cerrar la cerradura.

**Comment by kytos22** [comment]
Yo tambien tengo la cerradura. Los dispositivos de securitas se comunican con una conexion estilo zigbee a la alarma, pero entiendo que no se podria bypasear de forma sencilla esta comunicacion ya que no usan el estandar normal y ademas va cifrado. Lo suyo seria poder hacer todos las operaciones a traves de la API. Si @guerrerotook necesita mas detalles, dinos como podemos ayudar.

**Comment by guerrerotook** [comment]
Hola @kytos22, si eres capaz de encontrar una operación en la API que permita trabajar con la cerradura, perfecto, comparte la operación, que argumentos necesita y la implemento en la API.

**Comment by kytos22** [comment]
Ok creo que he sacado lo importante, no se hasta que punto son importantes las otras operaciones o si solo son para log y la interfaz.

Cuando le das click al boton para que salgan las opciones de bloquear y desbloquear solicita la configuracion de la cerradura con este JSON:

`​{"operationName":"xSGetSmartlockConfig","variables":{"numinst":"4579107","panel":"SDVECU","devices":[{"deviceType":"DR","deviceId":"02","keytype":"0"}]},"query":"query xSGetSmartlockConfig($numinst: String!, $panel: String!, $devices: [SmartlockDevicesInfo]!) {\n  xSGetSmartlockConfig(numinst: $numinst, panel: $panel, devices: $devices) {\n    res\n    referenceId\n    zoneId\n    serialNumber\n    location\n    family\n    label\n    features {\n      holdBackLatchTime\n      calibrationType\n      autolock {\n        active\n        timeout\n      }\n    }\n  }\n}"}`

Y la respuesta es:

`{"data":{"xSGetSmartlockConfig":[{"res":"OK","referenceId":null,"zoneId":"DR02","serialNumber":"xxxxxxxx","location":"Pl_0_Hall","family":"User","label":"Cerradura","features":{"holdBackLatchTime":0,"calibrationType":0,"autolock":{"active":true,"timeout":"1800"}}}]}}`

---

JSON Cuando le das a bloquar cerradura:

`{"operationName":"xSChangeSmartlockMode","variables":{"numinst":"xxxxxxxx","panel":"SDVECU","deviceId":"02","deviceType":"DR","lock":true},"query":"mutation xSChangeSmartlockMode($numinst: String!, $panel: String!, $deviceId: String!, $deviceType: String!, $lock: Boolean!) {\n  xSChangeSmartlockMode(\n    numinst: $numinst\n    panel: $panel\n    deviceId: $deviceId\n    deviceType: $deviceType\n    lock: $lock\n  ) {\n    res\n    msg\n    referenceId\n  }\n}"}`

Respuesta:

`{"data":{"xSChangeSmartlockMode":{"res":"OK","msg":"Your request has been sent","referenceId":"OWP_______________xxxxxxx__20241215180xxxxxx________________"}}}`

-----

JSON status mientras se cierra la cerradura:

`{"operationName":"xSChangeSmartlockModeStatus","variables":{"numinst":"xxxxxx","panel":"SDVECU","deviceId":"02","referenceId":"OWP_______________xxxxxxxx__202412151801xxxxx________________","counter":1},"query":"query xSChangeSmartlockModeStatus($numinst: String!, $panel: String!, $referenceId: String!, $deviceId: String, $counter: Int) {\n  xSChangeSmartlockModeStatus(\n    numinst: $numinst\n    panel: $panel\n    referenceId: $referenceId\n    counter: $counter\n    deviceId: $deviceId\n  ) {\n    res\n    msg\n    protomResponse\n    status\n  }\n}"}`

Respuesta (wait in progress):

`{"data":{"xSChangeSmartlockModeStatus":{"res":"WAIT","msg":"Request in progress, please wait","protomResponse":null,"status":null}}}`

Respuesta (OK):

`{"data":{"xSChangeSmartlockModeStatus":{"res":"OK","msg":"Request processed correctly","protomResponse":null,"status":"procesed"}}}`

-----
Resto JSON 1

`{"operationName":"xSGetSignals","variables":{"numinst":"xxxxxxx","panel":"SDVECU","deviceId":"02","referenceId":"OWP_______________xxxxxxx__2024121518xxxxxxxx________________","counter":3},"query":"query xSGetSignals($numinst: String!, $panel: String!, $referenceId: String!, $deviceId: String, $counter: Int!) {\n  xSGetSignals(\n    numinst: $numinst\n    panel: $panel\n    referenceId: $referenceId\n    deviceId: $deviceId\n    counter: $counter\n  ) {\n    res\n    status\n    signalResponse\n  }\n}"}`

respuesta (wait):

`{"data":{"xSGetSignals":{"res":"WAIT","status":null,"signalResponse":null}}}`

respuesta:

{"data":{"xSGetSignals":{"res":"OK","status":"procesed","signalResponse":"2"}}}

-----
Resto JSON 2

`{"header":{"callby":"OWP_10","provider":"OWA","appVersionName":"n/a","deviceManufacturer":"Firefox","deviceName":"Web Browser","deviceOsVersion":"133.0"},"events":[{"hash":"xxxx","callby":"OWP_10","application_raw":"KPI","appTimestamp":"2024-12-15 xxxxx","appTimestampEpoch":173428xxxx,"action":"CLICK","category":"SMARTLOCK","functionality":"SMARTLOCK_STATUS_CHANGE","screen":"SMARTLOCK_CARD","severity":"INFO","transactionId":"36a7ee91-6a47-4d28-9970-13xxxxxxx","numinst":"xxxxxxx","panel":"SDVECU","logMessage":"Start status: 1 - CLOSED","user":"xxxxxx"}]}`

Respuesta:

{"ok":true,"message":"Dump logging request accepted"}

-----
Resto JSON 3

`{"operationName":"xSGetLockCurrentMode","variables":{"numinst":"xxxxxxxx"},"query":"query xSGetLockCurrentMode($numinst: String!) {\n  xSGetLockCurrentMode(numinst: $numinst) {\n    res\n    smartlockInfo {\n      lockStatus\n      deviceId\n    }\n  }\n}"}`

respuesta:

`{"data":{"xSGetLockCurrentMode":{"res":"OK","smartlockInfo":[{"lockStatus":"2","deviceId":"02"}]}}}`

-----
Resto JSON 4

`{"header":{"callby":"OWP_10","provider":"OWA","appVersionName":"n/a","deviceManufacturer":"Firefox","deviceName":"Web Browser","deviceOsVersion":"133.0"},"events":[{"hash":"xxxxxx","callby":"OWP_10","application_raw":"KPI","appTimestamp":"2024-12-15 18:0xxxxx","appTimestampEpoch":1734xxxxxx,"action":"RENDER_OK","category":"SMARTLOCK","functionality":"SMARTLOCK_STATUS_CHANGE","screen":"SMARTLOCK_CARD","severity":"INFO","transactionId":"36a7ee91-6a47-4d28-9970-xxxxxxxxxxx","numinst":"xxxxxxxx","panel":"SDVECU","logMessage":"2 - CLOSEDKEY - Locked","duration":"8035","user":"xxxxxxxx"}]}`

respuesta:

`{"ok":true,"message":"Dump logging request accepted"}`

**Comment by CJHive** [comment]
Uno más que se une a la petición :)

**Comment by pacorola** [comment]
También me uno!

**Comment by kytos22** [comment]
@guerrerotook crees que se podrá integrar?

**Comment by guerrerotook** [comment]
Hola a todos y muchas gracias por compartir las operaciones de la API. Pero hasta el mes de febrero voy a estar liado con cosas del trabajo y con la UNED (que tengo exámenes) y no voy a poder dedicar mucho tiempo a hacer cosas nuevas. 

Pero dicho eso si alguien se anima a implementar hay que añadir un fichero nuevo lock.py e implementar esta operaciones. https://developers.home-assistant.io/docs/core/entity/lock 

La parte complicada de esto, es que yo no tengo ese cerrojo inteligente en mi casa y no puedo probarlo así que va a ser difícil.

**Comment by kytos22** [comment]
Hola, gracias por la respuesta. Yo aunque puedo entender gran parte del codigo y puedo hacer scripts no me dedico a programar, pero le echare un vistazo. Por otro lado yo me puedo ofrecer a hacer las pruebas que hagan falta. Si se te ocurre otro consejo que darme para ponerme a ello me dices.

**Comment by guerrerotook** [comment]
Se necesitan nociones de python para programar y necesitas Docker y Visual Studio Code para ejecutar una version de desarrollo de Home Assistant donde tengas la integración de la alarma y puedas depurar y poner puntos de ruptura y todo eso.

**Comment by CJHive** [comment]
No se, si se puede hacer una zona beta como otro github aparte de este para hacer las betas o en la versiones una versión beta para que los que tengan cerraduras, cámaras, perimetrales.... etc puedan probar y ver si falla algo.

Yo 0 de programación. Intenté hacer algo con la ia de bolt pero sin logros, supongo que por las apis. 

Por si alguno la quiere ver https://bolt.new/ está chulo

**Comment by kytos22** [comment]
Intentaré hacer algo estos dias en un fork, pero no espereis nada serio de mis experimentos.

Valores API:

En operacion" xSGetLockCurrentMode":

"lockStatus": "1" = unlocked
"lockStatus": "2", = locked

En operacion "xSChangeSmartlockMode":
  Variable:  lock: false = Unlock
  Variable:  lock: true = Lock

**Comment by pacorola** [comment]
Otro más que se une a la petición!!!! Y se ofrece a hacer testing si es necesario

**Comment by pacorola** [comment]
@kytos22, he visto tu fork y me ofrezco para ayudarte si necesitas probando, de momento me he copiado apimanager y lock.py a mi instalación pero no veo cambios tras reiniciar. Millones de gracias por el esfuerzo!!! Tiene muy buena pinta y marcará un antes y un después para muchos!!!!

**Comment by kytos22** [comment]
Hola, no uses mi desarrollo, ahora mismo es un popurrí de codigo de prueba que no sirve para nada, y con el cambio de trabajo no he tenido tiempo de indagar mas. Habrá que esperar a otro aportador. No deberia ser muy dificil para alguien que tenga experiencia, simplemente dar soporte al dispositivo en la implementación y meter y probar las llamadas a la api.

**Comment by pacorola** [comment]
Gracias! Ánimo con el nuevo reto. Ojalá supiese como aportar más, un abrazo!!!

**Comment by hlas** [comment]
Hola

He encontrado un poco de tiempo libre y he hecho un primer intento que más
o menos me funciona.

Faltan bastantes cosas por refinar, pero por algo se empieza

https://github.com/hlas/securitas-direct-new-api-with-lock.git

**Comment by pacorola** [comment]
> Hola
> 
> He encontrado un poco de tiempo libre y he hecho un primer intento que más
> o menos me funciona.
> 
> Faltan bastantes cosas por refinar, pero por algo se empieza
> 
> https://github.com/hlas/securitas-direct-new-api-with-lock.git

Que bien!!! Quieres que lo pruebe y te mande un debug?

**Comment by CJHive** [comment]
Para mi es funcional :) abre y cierra ahora es añadirlo a una automatización

**Comment by Cobretti75** [comment]
Hola a tod@s!
En primer lugar, quería daros las gracias por vuestra generosidad compartiendo vuestro trabajo para poder tener la cerradura electrónica en esta integración.
A nosotros nos la instalaron hace tan solo 1 semana y llevo unos días probando estas aportaciones realizadas por @hlas. Y el caso es que me funciona que salga el estado de la cerradura pero solo al iniciarse la integración, después ya no detecta cuando cambia el estado de bloqueada a desbloqueada y al revés. Al menos no inmediatamente o en pocos minutos (cuando espero al menos 20 minutos sí parece que lo hace). Y tampoco me funciona poder bloquearla y desbloquearla desde Home Assistant. Así que no sé qué estoy haciendo mal. ¿A vosotros os funciona todo bien?. Gracias de antemano!

**Comment by pacofran955** [comment]
Tengo configurados tarjetas nfc en el sótano y terraza de la planta primera por si abro sin quitar la alarma, no tener que bajar corriendo a la planta baja a quitar la alarma y la verdad que funcionan muy bien.

Quería hacer lo mismo con la cerradura para poder abrir por NFC pero tengo los problemas antes descritos, muchas gracias a los desarrolladores de antemano

**Comment by pacofran955** [comment]
La cerradura es el modelo nuevo, lo cambiaron hace unos meses

**Comment by pacofran955** [comment]
Si queréis que saque algún tipo más de información de la cerradura indicármelo, pero me tenéis que decir cómo, mis conocimientos son limitadas

**Comment by pops3449** [comment]
Hola, hace unos días actualicé el modulo Securitas (en Chile) que funcionaba correctamente. Luego de la actualización, ya no permite conectar o desconectar la alarma. Los registros de error son prácticamente los mismos que presenta @pacofran955. El primero corresponde al intento de poner la alarma de noche (que no se habilitó), y el segundo al intentar desconectarla (se había habilitado con la app Verisure).

**Primero:**
Registrador: homeassistant.components.websocket_api.http.connection
Fuente: components/websocket_api/commands.py:258
integración: Home Assistant WebSocket API (documentación, problemas)
Ocurrió por primera vez: 08:58:57 (5 ocurrencias)
Última vez registrado: 19:22:25

[546432991776] Unexpected exception
[546623149280] Unexpected exception
[546140025408] Unexpected exception
[546066969472] Unexpected exception
[546500674240] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 258, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2799, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2842, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1011, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1083, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 309, in async_handle_alarm_arm_night
    await self.async_alarm_arm_night(self.check_code_arm_required(code))
  File "/config/custom_components/securitas/alarm_control_panel.py", line 296, in async_alarm_arm_night
    await self.set_arm_state(AlarmControlPanelState.ARMED_NIGHT)
  File "/config/custom_components/securitas/alarm_control_panel.py", line 262, in set_arm_state
    arm_status = await self.client.session.arm_alarm(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.installation, self.state_map[mode]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 653, in arm_alarm
    if response["res"] != "OK":
       ~~~~~~~~^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Segundo:**
Registrador: homeassistant.components.websocket_api.http.connection
Fuente: components/websocket_api/commands.py:258
integración: Home Assistant WebSocket API (documentación, problemas)
Ocurrió por primera vez: 08:58:59 (6 ocurrencias)
Última vez registrado: 19:23:01

[546432991776] Unexpected exception
[546623149280] Unexpected exception
[546140025408] Unexpected exception
[546500674240] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 258, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2799, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2842, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1011, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
        hass, entity, func, data, call.context
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1083, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py", line 270, in async_handle_alarm_disarm
    await self.async_alarm_disarm(self.code_or_default_code(code))
  File "/config/custom_components/securitas/alarm_control_panel.py", line 239, in async_alarm_disarm
    disarm_status = await self.client.session.disarm_alarm(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        self.installation
        ^^^^^^^^^^^^^^^^^
    )
    ^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 720, in disarm_alarm
    if "res" in response and response["res"] != "OK":
       ^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

**Comment by jmrevuelta** [comment]
Me funciona perfectamente la cerradura electronica con Home Assistant. Pero sólo puedo bloquearla y desbloquearla. Necesitaría incluir la opción de apertura de puerta que es diferente a las anteriores.
