### ISSUE TITLE
Sensors don't work again; Air Quality, Humidity and Temperature

### ISSUE THREAD

**Issue by montoyra** [guerrerotook/securitas-direct-new-api#241]
Sensors don't work again; Air Quality, Humidity and Temperature
This entity is no longer provided by the securitas integration from yesterday afternoon

**Comment by montoyra** [comment]
Hi, this is the error in log:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/securitas/sensor.py", line 42, in async_setup_entry
    sentinel_data: Sentinel = await client.session.get_sentinel_data(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 505, in get_sentinel_data
    response = await self._execute_request(content, "Sentinel")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 177, in _execute_request
    response_dict["errors"][0]["message"], response_dict, headers, content
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'message'

**Comment by jmatiasGH** [comment]
2024-07-18 21:25:50.944 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up securitas platform for sensor
File "/config/custom_components/securitas/sensor.py", line 42, in async_setup_entry
File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 505, in get_sentinel_data
File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 177, in _execute_request
2024-07-18 21:25:55.160 ERROR (MainThread) [homeassistant.helpers.service] Failed to load integration: securitas

**Comment by vixium** [comment]
same here, deleted integration, re-downloaded and installed again:
only alarm detected...

> Registrador: homeassistant.components.sensor
Fuente: helpers/entity_platform.py:364
integración: Sensor (documentación, problemas)
Ocurrió por primera vez: 19:07:07 (2 ocurrencias)
Último inicio de sesión: 19:36:49
Error while setting up securitas platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 364, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/securitas/sensor.py", line 42, in async_setup_entry
    sentinel_data: Sentinel = await client.session.get_sentinel_data(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 505, in get_sentinel_data
    response = await self._execute_request(content, "Sentinel")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 177, in _execute_request
    response_dict["errors"][0]["message"], response_dict, headers, content
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'message'

**Comment by samatild** [comment]
I can confirm that is also not working at my end.

```python
"/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 177, in _execute_request
response_dict["errors"][0]["message"], response_dict, headers, content
~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'message'
```
we are trying to access the 'message' key in the dictionary but it does not exist. I wonder what verisure/securitas changed on their side again.

maybe we can extract the error info from data field in the message itself that we have from debug:
```
2024-07-26 13:59:37.466 DEBUG (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] {"data":{"xSAllConfort":null},"errors":[{"data":{"name":"accessPermissionsMiddleware","reason":"accessPermissions: Missing capabilities data"}}]}
```

**Comment by OkOtChA666** [comment]
Same

**Comment by aritztg** [comment]
Another one here with this

**Comment by vixium** [comment]
I think this project is dead

**Comment by Juanen2** [comment]
In my case sensors have been re-detected and now are available with the same name but with an _2 suffix. Just make sure to delete the old ones and everything should work fine. Also make sure with recent updates HACS is working fine.

**Comment by kytos22** [comment]
In my case are working too. When I integrated my alarm they were not working anyway, so now i just have the sensors.
