### ISSUE TITLE
Error while setting up securitas platform for sensor

### ISSUE THREAD

**Issue by Tanjohnson99** [guerrerotook/securitas-direct-new-api#253]
Hello,

Every day, i have this error.

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:361
integration: Sensor (documentation, issues)
First occurred: 18:24:13 (1 occurrences)
Last logged: 18:24:13

Error while setting up securitas platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 361, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/securitas/sensor.py", line 42, in async_setup_entry
    sentinel_data: Sentinel = await client.session.get_sentinel_data(
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 505, in get_sentinel_data
    response = await self._execute_request(content, "Sentinel")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 177, in _execute_request
    response_dict["errors"][0]["message"], response_dict, headers, content
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'message'

**Comment by masterFONSI** [comment]
Same here, don't have readings on my sensors

**Comment by guerrerotook** [comment]
This should be solved in the next release V2.8 where I add a missing parameter when calling the API.
