### ISSUE TITLE
Error de instalación

### ISSUE THREAD

**Issue by grumete** [guerrerotook/securitas-direct-new-api#31]
Ante todo gracias por tu trabajo para la Comunidad.
Me reporta este error que no sé como solucionarlo:

Este error se originó a partir de una integración personalizada.

Logger: homeassistant.setup
Source: custom_components/securitas/__init__.py:109
Integration: securitas (documentation, issues)
First occurred: 10:16:07 (1 occurrences)
Last logged: 10:16:07

Error during setup of component securitas
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 227, in _async_setup_component
    result = await task
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/securitas/__init__.py", line 64, in setup
    if not HUB.login():
  File "/config/custom_components/securitas/__init__.py", line 109, in login
    if service.description == sentinel_value:
AttributeError: 'str' object has no attribute 'description'

Y seguidamente este otro:

Este error se originó a partir de una integración personalizada.

Logger: custom_components.securitas.securitas_direct_new_api.apimanager
Source: custom_components/securitas/securitas_direct_new_api/apimanager.py:102
Integration: securitas (documentation, issues)
First occurred: 10:16:07 (1 occurrences)
Last logged: 10:16:07

Ha ocurrido un problema, reintente la acción o póngase en contacto con nosotros.

Que debo hacer? Gracias.

**Comment by guerrerotook** [comment]
Por lo que veo en los logs, el fichero se llama init.py y no __init__.py, cuidado con eso. Te recomiendo que lo instales desde aquí, https://hacs.xyz/ que es más fácil.

**Comment by soth78** [comment]
Hay un monton de texto (como dices, con informacion privada) y luego el error:

```
2022-02-13 21:17:06 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Error while setting up securitas platform for alarm_control_panel
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/securitas/alarm_control_panel.py", line 65, in async_setup_entry
current_state: CheckAlarmStatus = await client.update_overview(
File "/config/custom_components/securitas/__init__.py", line 265, in update_overview
await self.hass.async_add_executor_job(sleep(1))
File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
TypeError: 'NoneType' object is not callable
```

Esto te sirve?

**Comment by guerrerotook** [comment]
Pues viendo los logs la verdad es que no mucho, porque veo que el error es porque no existe un objeto pero no entiendo por qué. Aparece algún otro tipo de menaje previo que creas que es relevante?

¿Puedes probar a poner en la configuración la opcion de check_alarm_panel: false?

`check_alarm_panel: false`

En otro orden de cosas, te aparece el panel de alarma en el Home Assistant?

**Comment by soth78** [comment]
Buenas,

Cambiando esa configuracion funciona bien (carga, no lo he accionado pero el panel ahora carga).

Poniendola a True o true (he probado ambas, por si acaso) deja de funcionar, y veo el dispositivo como "no disponible"

**Comment by guerrerotook** [comment]
Voy a cerrar esto por ahora y si te da más problemas lo vemos.
