### ISSUE TITLE
Country error

### ISSUE THREAD

**Issue by jsole** [guerrerotook/securitas-direct-new-api#54]
Hi! I was using your integration for my alarm and after updating from v1.0.0.0 I have this error:

2022-05-05 20:13:25 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 219, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 205, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 62, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 260, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/securitas/config_flow.py", line 107, in async_step_user
    user_input[CONF_COUNTRY],
KeyError: 'country'

My configuration.yml has the country as shown in the readme:

securitas:
  username: !secret verisure_username
  password: !secret verisure_password
  code: !secret verisure_code
  country: ES
  check_alarm_panel: false

I'm I missing something? Thanks!

**Comment by guerrerotook** [comment]
If you are using the integration from spain, remove the country configuration and it will work by default.

**Comment by jsole** [comment]
Hi Just tried to update to v1.2.2.0  and remove the country configuration and it does not initiate the component.

The configuration now looks like this:

securitas:
username: !secret verisure_username
password: !secret verisure_password
code: !secret verisure_code

2022-06-02 22:09:07 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-02 22:10:07 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-02 22:11:07 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-02 22:12:07 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas

Any other ideas?  v1.0.0.0 seems to work ok, so i'm not sure what could be the problem.

Thanks for your help!

**Comment by guerrerotook** [comment]
I don't see in your configuration the country nor the language, did you configure that properly?

**Comment by jsole** [comment]
Hi! I updated to the vew version V1.3.0.0 as it stopped working due to the login changes and it's working well again. 

I'm using now this config:

```
securitas:
  username: !secret verisure_username
  password: !secret verisure_password
  code: !secret verisure_code
  country: ES
  check_alarm_panel: true
```
Thanks for everything!
