### ISSUE TITLE
Integration stopped working - different URL maybe?

### ISSUE THREAD

**Issue by mvillarejo** [guerrerotook/securitas-direct-new-api#56]
Hello,

Integration has stopped working since a couple of days ago and the logs are reflecting this:
```
 customers.securitasdirect.es:443 ssl:default [Connection reset by peer] 
```

does anyone know if the URL has changed for Securitas?

cheers

**Comment by mvillarejo** [comment]
looks like is ok now but having a different issue:
```
2022-06-03 09:46:00 ERROR (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Lo sentimos. No se ha podido realizar la acción solicitada.
2022-06-03 09:46:00 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/securitas/alarm_control_panel.py", line 58, in async_setup_entry
    current_state: CheckAlarmStatus = await client.update_overview(
  File "/config/custom_components/securitas/__init__.py", line 282, in update_overview
    while alarm_status.operation_status == "WAIT":
AttributeError: 'str' object has no attribute 'operation_status'
```

**Comment by mvillarejo** [comment]
this can be closed, was a local issue.
