### ISSUE TITLE
Failed to initiate securitas custom component

### ISSUE THREAD

**Issue by siom7** [guerrerotook/securitas-direct-new-api#6]
Hi !

I tried to use your integration but I have following errors, if I restart my HA sometimes it's working and I can arm/disarm my alarm one time and after few seconds the component won't arm or disarm the alarm and no status reported. If I check history directly on the website I have following message "error while processing your request, please try later".

2021-12-16 13:11:07 WARNING (MainThread) [homeassistant.components.alarm_control_panel] Setup of alarm_control_panel platform securitas_direct is taking over 10 seconds.
2021-12-16 13:11:52 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: alarm_control_panel.securitas_direct
2021-12-16 13:11:57 ERROR (MainThread) [homeassistant.components.alarm_control_panel] Setup of platform securitas_direct is taking longer than 60 seconds. Startup will proceed without waiting any longer.
2021-12-16 13:12:34 ERROR (SyncWorker_9) [custom_components.securitas_direct.securitas_direct_new_api.apimanager] Votre demande n'a pas pu être transmise ; veuillez réessayer dans quelques minutes
2021-12-16 13:12:34 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/securitas_direct/alarm_control_panel.py", line 55, in setup_platform
    current_state: CheckAlarmStatus = hub.update_overview(
  File "/usr/src/homeassistant/homeassistant/util/__init__.py", line 195, in wrapper
    result = method(*args, **kwargs)
  File "/config/custom_components/securitas_direct/__init__.py", line 121, in update_overview
    alarmStatus = self.session.checkAlarmStatus(Installation, referenceId)
  File "/config/custom_components/securitas_direct/securitas_direct_new_api/apimanager.py", line 198, in checkAlarmStatus
    raw_data["res"],
TypeError: 'NoneType' object is not subscriptable

Thanks for your help.

**Comment by siom7** [comment]
The problem seems located on Securitas side, arm/disarm and status update doesn't work from mobile app...
