### ISSUE TITLE
home assistant fails to start integration after reboot

### ISSUE THREAD

**Issue by fulviomeomartini** [guerrerotook/securitas-direct-new-api#62]
Hello,
I probably explained myself wrong in #60 .
I can't get securitas to start after a reboot. I tried to reinstall the integration but nothing. I show you a screenshot and my errors:
<img width="734" alt="Schermata 2022-06-26 alle 10 36 15" src="https://user-images.githubusercontent.com/93532601/175806533-54d70894-16b9-46ba-b97f-e0dfc5633d90.png">

2022-06-26 10:31:40 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-26 10:32:40 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-26 10:33:36 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward
2022-06-26 10:33:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/securitas/config_flow.py", line 115, in async_step_import
  File "/config/custom_components/securitas/config_flow.py", line 84, in _create_client
Exception: error login
2022-06-26 10:33:41 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-26 10:34:41 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-26 10:35:41 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-26 10:36:41 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-26 10:37:41 WARNING (MainThread) [homeassistant.bootstrap] Waiting on integrations to complete setup: securitas
2022-06-26 10:38:36 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for bootstrap - moving forward

**Comment by fulviomeomartini** [comment]
i also found this:


Questo errore ha avuto origine da un'integrazione personalizzata.

Logger: homeassistant
Source: custom_components/securitas/securitas_direct_new_api/apimanager.py:67
Integration: Securitas Direct (documentation, issues)
First occurred: 12:30:47 (1 occurrences)
Last logged: 12:30:47

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1154, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 880, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 861, in getaddrinfo
    return await self.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/socket.py", line 954, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 205, in async_init
    flow, result = await task
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 232, in _async_init
    result = await self._async_handle_step(flow, flow.init_step, data, init_done)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/securitas/config_flow.py", line 115, in async_step_import
    return await self._create_client(
  File "/config/custom_components/securitas/config_flow.py", line 82, in _create_client
    succeed: bool = await securitas.login()
  File "/config/custom_components/securitas/__init__.py", line 235, in login
    succeed: tuple[bool, str] = await self.session.login()
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 132, in login
    response: ClientResponse = await self._execute_request(content)
  File "/config/custom_components/securitas/securitas_direct_new_api/apimanager.py", line 67, in _execute_request
    async with self.http_client.post(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1166, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host customers.verisure.it:443 ssl:default [Try again]

**Comment by fulviomeomartini** [comment]
i add my configuration.yaml file:
securitas:
  username: !secret securitas_direct_username
  password: !secret securitas_direct_password
  code: !secret securitas_direct_code
  country: IT
  check_alarm_panel: false

**Comment by jmatiasGH** [comment]
That happens to me too. I have seen that on the Securitas Direct website they have activated a double authentication factor, surely it remains in the step of sending the SMS and entering the code they send.

**Comment by guerrerotook** [comment]
Close because of duplicate issue #52
