### ISSUE TITLE
Unknown error occurred after confirming phone code

### ISSUE THREAD

**Issue by itdap77** [guerrerotook/securitas-direct-new-api#84]
Hello, I was not ablet to make the new integration to run propertly. I was able to get the notification code on my phone but later i am getting Unknown error and then "Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble"

Do you have any idea what could be the issue? Where i can see the debug logs?

**Comment by guerrerotook** [comment]
The logs can be seen in the home-assistant.log file. Can you provide more information?

**Comment by itdap77** [comment]
Logger: aiohttp.server
Source: custom_components/securitas/config_flow.py:145
Integration: Securitas Direct ([documentation](https://github.com/guerrerotook/securitas-direct-new-api), [issues](https://github.com/guerrerotook/securitas-direct-new-api/issues))
First occurred: 10:24:17 PM (1 occurrences)
Last logged: 10:24:17 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 171, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 96, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/securitas/config_flow.py", line 145, in async_step_otp_challange
    await self.securitas.send_sms_code(self.opt_challange[0], user_input[CONF_CODE])
TypeError: 'NoneType' object is not subscriptable

**Comment by Nodezero1** [comment]
I'm having the same problem.  I am able to get as far as entering the SMS code in the config flow.  As soon as I enter the code, it says Error and won't let me continue.  Using V2.1.0.1. Please find the log below:

2023-02-21 09:04:24.136 ERROR (MainThread) [custom_components.securitas.securitas_direct_new_api.apimanager] Unauthorized
2023-02-21 09:04:40.932 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 341, in _async_handle_step
    if not isinstance(result["type"], FlowResultType):
TypeError: 'bool' object is not subscriptable
2023-02-21 09:04:40.940 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1365, in async_forward_entry_setup
    await entry.async_setup(self.hass, integration=integration)
AttributeError: 'collections.OrderedDict' object has no attribute 'async_setup'
2023-02-21 09:04:40.941 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1365, in async_forward_entry_setup
    await entry.async_setup(self.hass, integration=integration)

**Comment by guerrerotook** [comment]
I see, can you download the latest version, https://github.com/guerrerotook/securitas-direct-new-api/releases/tag/v2.1.0.2 that fix an issue with the config flow?

**Comment by Nodezero1** [comment]
With V2.1.0.2 I can't even get to the based the first page in the config flow, once I enter my account info it says Unknown Error Occurred with the following log:

2023-02-21 13:39:44.031 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 227, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 145, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 253, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 335, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/securitas/config_flow.py", line 160, in async_step_user
    initial_data[CONF_ENTRY_ID],
KeyError: 'entry_id'

**Comment by guerrerotook** [comment]
Let me create a new release for this fix.

**Comment by guerrerotook** [comment]
Can you try this release? https://github.com/guerrerotook/securitas-direct-new-api/releases/tag/v2.1.0.3

**Comment by Nodezero1** [comment]
It's working perfectly.  I appreciate your effort, thanks!
